[settings]
lockfile = true
locked = true
minimum_release_age = "7d"

[tools]
hk = { version = "1.54.1", postinstall = "hk install --mise" }
betterleaks = "latest"
cocogitto = "latest"
actionlint = "latest"
zizmor = "latest"
node = "22"
npm = "11"
pnpm = "11"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]
